/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 184d523e9d8021f485f41cfe1fd9df81)
interface __BaseEnv_Env {
	GITHUB_REPOSITORY: "ohxiyu/bmtnews-standalone";
	GITHUB_WORKFLOW: "daily-summary.yml";
	GITHUB_REF: "main";
	EDITION_TIMEZONE: "Asia/Shanghai";
	EDITION_CUTOFF_HOUR: "8";
	PUBLIC_SITE_URL: "https://ohxiyu.github.io/bmtnews";
	GITHUB_DISPATCH_TOKEN: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_REPOSITORY" | "GITHUB_WORKFLOW" | "GITHUB_REF" | "EDITION_TIMEZONE" | "EDITION_CUTOFF_HOUR" | "PUBLIC_SITE_URL" | "GITHUB_DISPATCH_TOKEN">> {}
}
