/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: a171744514512eb4ccd852f43c778673)
interface __BaseEnv_Env {
	GITHUB_REPOSITORY: "ohxiyu/bmtnews-standalone";
	GITHUB_WORKFLOW: "daily-summary.yml";
	GITHUB_REF: "main";
	EDITION_TIMEZONE: "Asia/Shanghai";
	EDITION_CUTOFF_HOUR: "8";
	PUBLIC_SITE_URL: "https://bmt.news";
	GITHUB_DISPATCH_TOKEN: string;
	RECOVERY_CHECK_TOKEN: string;
	PAGES_DEPLOY_HOOK: string;
	RECOVERY_GATE: DurableObjectNamespace<import("./src/index").RecoveryGate>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "RecoveryGate";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "GITHUB_REPOSITORY" | "GITHUB_WORKFLOW" | "GITHUB_REF" | "EDITION_TIMEZONE" | "EDITION_CUTOFF_HOUR" | "PUBLIC_SITE_URL" | "GITHUB_DISPATCH_TOKEN" | "RECOVERY_CHECK_TOKEN" | "PAGES_DEPLOY_HOOK">> {}
}
